using CSMWebCore.Data;
using CSMWebCore.Entities;
using CSMWebCore.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSMWebCore.Services
{
    public class ServicePriceData : IServicePriceData
    {
        private ChipsDbContext _db;
        public ServicePriceData(ChipsDbContext db)
        {
            _db = db;
        }
        //method that takes a list of LogTypes and returns the total cost of those services
        //the list of services are generated by the SQLLogData.cs and are distinct
        public decimal GetTotalPriceOfTicket(Ticket ticket)
        {
            decimal total = 0.00m;
            IEnumerable<Log> logs = ticket.Logs;
            foreach (Log log in logs)
            {
                total += log.Event.Price;
            }
            return total;
        }

        public decimal GetPriceOfLogEvent(Event e)
        {
            return e.Price;
        }
    }
}
