using CSMWebCore.Data;
using CSMWebCore.Entities;
using CSMWebCore.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSMWebCore.Services
{
    public class SqlServicePriceData : IServicePriceData
    {
        private ChipsDbContext _db;
        public SqlServicePriceData(ChipsDbContext db)
        {
            _db = db;
        }
        //method that takes a list of LogTypes and returns the total cost of those services
        //the list of services are generated by the SQLLogData.cs and are distinct
        public decimal GetTotalPrice(IEnumerable<LogType> services)
        {
            decimal total = 0.00m;
            foreach (LogType service in services)
            {
                total += _db.ServicePrices.SingleOrDefault(x => x.Service == service).Price;
            }
            return total;
        }
        public decimal GetPriceOfServiceType(LogType service)
        {
            return _db.ServicePrices.SingleOrDefault(x => x.Service == service).Price;
        }

    }
}
